FROM ubuntu:latest

RUN apt-get update
RUN apt-get install python3 -y
RUN apt install software-properties-common -y
RUN add-apt-repository --yes --update ppa:ansible/ansible
RUN apt-get install ansible -y

CMD ["sh", "-c", "tail -f /dev/null"]
